"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-07-07 18:46:34.373665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('cleaned_text', sa.Text(), nullable=False),
    sa.Column('selected_text', sa.Text(), nullable=False),
    sa.Column('raw_hash', sa.Text(), nullable=True),
    sa.Column('sha256_hash', sa.Text(), nullable=False),
    sa.Column('bias_score', sa.Float(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles'))
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_id'), ['id'], unique=False)

    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
    sa.UniqueConstraint('name', name=op.f('uq_entities_name'))
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_id'), ['id'], unique=False)

    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_name', sa.Text(), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('tldr_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles'))
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_id'), ['id'], unique=False)

    op.create_table('facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fact_id', sa.Text(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('fact_type', sa.Text(), nullable=False),
    sa.Column('fact_date', sa.Date(), nullable=True),
    sa.Column('fact_text', sa.Text(), nullable=False),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('role_context', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_facts_article_id_articles')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_facts_profile_id_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facts')),
    sa.UniqueConstraint('fact_id', name=op.f('uq_facts_fact_id'))
    )
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facts_id'), ['id'], unique=False)

    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('target_name', sa.Text(), nullable=False),
    sa.Column('target_profile_id', sa.Integer(), nullable=True),
    sa.Column('target_entity_id', sa.Integer(), nullable=True),
    sa.Column('rel_type', sa.Text(), nullable=False),
    sa.Column('target_kind', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('dismissed_links', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_relationships_article_id_articles')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_relationships_profile_id_profiles')),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], name=op.f('fk_relationships_target_entity_id_entities')),
    sa.ForeignKeyConstraint(['target_profile_id'], ['profiles.id'], name=op.f('fk_relationships_target_profile_id_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationships'))
    )
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationships_id'), ['id'], unique=False)

    op.create_table('contradictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('new_fact_id', sa.Integer(), nullable=False),
    sa.Column('contradicted_fact_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contradicted_fact_id'], ['facts.id'], name=op.f('fk_contradictions_contradicted_fact_id_facts')),
    sa.ForeignKeyConstraint(['new_fact_id'], ['facts.id'], name=op.f('fk_contradictions_new_fact_id_facts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contradictions'))
    )
    with op.batch_alter_table('contradictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contradictions_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contradictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contradictions_id'))

    op.drop_table('contradictions')
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationships_id'))

    op.drop_table('relationships')
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facts_id'))

    op.drop_table('facts')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_id'))

    op.drop_table('profiles')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_id'))

    op.drop_table('entities')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_id'))

    op.drop_table('articles')
    # ### end Alembic commands ###
